### ISSUE TITLE
Crash with the newest Thermal expansion

### ISSUE THREAD

**Issue by Spirevipp** [BRForgers/IndustrialExpansion-1.12.2#1]
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IndustrialExpansion (IndustrialExpansion)
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/util/crafting/CompactorManager$Mode`

Thermal expansion updated a few days ago, also releasing thermal dynamics. It seems like they have renamed some crafting systems.

ThermalFoundation-1.10.2-2.1.0.82-universal.jar
ThermalExpansion-1.10.2-5.1.1.93-universal.jar
ThermalDynamics-1.10.2-2.0.2.4-universal.jar
IndustrialExpansion-1.1.1.jar

**Comment by a-frenzy** [comment]
same https://gist.github.com/frenzye/5756bb8d457dcc7c90bd4f278945caec

**Comment by allanf181** [comment]
https://github.com/BRForgers/IndustrialExpansion-1.10.2/commit/0163a8b62dcf6c6fe1597a92e71c0318d6e69cd8

**Comment by allanf181** [comment]
Fixed on https://github.com/BRForgers/IndustrialExpansion-1.10.2/commit/0163a8b62dcf6c6fe1597a92e71c0318d6e69cd8
