### ISSUE TITLE
Server crash with after updating TE

### ISSUE THREAD

**Issue by Xiaminou** [BRForgers/IndustrialExpansion-1.12.2#5]
[crash-2018-01-02_18.16.47-server.txt](https://github.com/BRForgers/IndustrialExpansion-1.12.2/files/1598202/crash-2018-01-02_18.16.47-server.txt)

**Comment by MasterEnderman** [comment]
https://pastebin.com/EgtVg3LP

**Comment by Xiaminou** [comment]
Oh wait this is Industrial Expansion and not Industrial Foregoing, my bad, issue needs to be re-opened.
