### ISSUE TITLE
Server crash with latest TE

### ISSUE THREAD

**Issue by Dalethium** [BRForgers/IndustrialExpansion-1.12.2#7]
[Crash report](https://pastebin.com/egzr7TGz)

TE was just updated a few hours ago

**Comment by Charismara** [comment]
I have the same problem 😢

**Comment by MasterEnderman** [comment]
The Client crashes as well on startup: https://pastebin.com/TfKy9M2r

**Comment by maroontin** [comment]
Also a crash on client startup https://pastebin.com/M47EgHsr

**Comment by ACGaming** [comment]
Can confirm this.
