### ISSUE TITLE
Unable to remove recipe with craftweaker

### ISSUE THREAD

**Issue by Thedrummonger** [BRForgers/IndustrialExpansion-1.12.2#8]
After adding a script to remove certain recipes in this mod with craftweaker, the recipes are still available when the game is loaded. The script is correct and does not show any errors, it seems that recipes may be loaded after craftweaker attempts to remove them. I have replicated this issue in a pack with only Industrial Expantion, JEI and craftweaker.
---
IndustrialExpantion-1.2.6
CraftTweaker2-1.12-4.1.9
forge-14.23.4.2739

**Comment by allanf181** [comment]
What recipes?

**Comment by Thedrummonger** [comment]
The recipes for the armor.

**Comment by allanf181** [comment]
Probably is a CraftTweaker2 issue.
